version: '3.8'
services:
  redis-sentinel-m:
    image: bitnami/redis-sentinel
    restart: unless-stopped
    ports:
      - '${SENTINEL_OUTPORT}:26379'
    environment:
      - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
      - REDIS_MASTER_PORT_NUMBER=${MASTER_OUTPORT}
      - REDIS_MASTER_PASSWORD=${MASTER_PASSWORD}
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=${REDIS_SENTINEL_QUORUM}
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=${REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS}
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=${REDIS_SENTINEL_FAILOVER_TIMEOUT}
      - REDIS_SENTINEL_ANNOUNCE_IP=${REDIS_SENTINEL_ANNOUNCE_IP}
      - REDIS_SENTINEL_ANNOUNCE_PORT=${SENTINEL_OUTPORT}
  
