version: '3.8'
services:
  sentinel:
    image: bitnami/redis-sentinel
    restart: always
    mem_limit: 2g
    cpus: 2
    ports:
      - '${SENTINEL_OUTPORT}:6565'
    environment:
      - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
      - REDIS_MASTER_PORT_NUMBER=${MASTER_OUTPORT}
      - REDIS_MASTER_PASSWORD=${MASTER_PASSWORD}
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=${REDIS_SENTINEL_QUORUM}
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=${REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS}
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=${REDIS_SENTINEL_FAILOVER_TIMEOUT}
      - REDIS_SENTINEL_ANNOUNCE_IP=${REDIS_SENTINEL_ANNOUNCE_IP}
      - REDIS_SENTINEL_ANNOUNCE_PORT=${REDIS_SENTINEL_ANNOUNCE_PORT}
      - REDIS_SENTINEL_PORT_NUMBER=${REDIS_SENTINEL_PORT_NUMBER}
      - REDIS_SENTINEL_PASSWORD=${MASTER_PASSWORD}
   # network_mode: "host"
  
